### This concludes the tutorial for IBM_C2W3L1



In [7]:
import numpy as np
import pandas as pd

In [2]:
a = np.ones([2,3,3]) # 2 x 3 x 3 tensor

In [3]:
a

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

In [4]:
b = np.ones([2,2,3,3])

In [5]:
b

array([[[[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]]],


       [[[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]]]])

In [6]:
c = np.ones([2,2,2,3,3])

In [7]:
c

array([[[[[1., 1., 1.],
          [1., 1., 1.],
          [1., 1., 1.]],

         [[1., 1., 1.],
          [1., 1., 1.],
          [1., 1., 1.]]],


        [[[1., 1., 1.],
          [1., 1., 1.],
          [1., 1., 1.]],

         [[1., 1., 1.],
          [1., 1., 1.],
          [1., 1., 1.]]]],



       [[[[1., 1., 1.],
          [1., 1., 1.],
          [1., 1., 1.]],

         [[1., 1., 1.],
          [1., 1., 1.],
          [1., 1., 1.]]],


        [[[1., 1., 1.],
          [1., 1., 1.],
          [1., 1., 1.]],

         [[1., 1., 1.],
          [1., 1., 1.],
          [1., 1., 1.]]]]])

In [2]:
import types
import pandas as pd
from botocore.client import Config
import ibm_boto3

def __iter__(self): return 0

# @hidden_cell
# The following code accesses a file in your IBM Cloud Object Storage. It includes your credentials.
# You might want to remove those credentials before you share the notebook.
# rm credentials


body = client_e364cda5223243e58471d0943f25de0c.get_object(Bucket='ibmc2w3l1-donotdelete-pr-h5yaau91q3srxz',Key='CTDunknown.csv')['Body']
# add missing __iter__ method, so pandas accepts body as file-like object
if not hasattr(body, "__iter__"): body.__iter__ = types.MethodType( __iter__, body )

df_data_1 = pd.read_csv(body)
df_data_1.head()


p        S        t
0  1  35.5419  27.4180
1  3  35.5408  27.4281
2  5  35.5441  27.4355
3  7  35.5488  27.4374
4  9  35.5524  27.4419

In [8]:
np.shape(df_data_1)

(751, 3)